### ISSUE TITLE
base40.h show build errors v0.9.3.1

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#101]
base40.h , written by Lizhi?, show build errors v0.9.3.1
Not a stopper but should be easy to fix?

In file included from utilitydialog.cpp:38:0:
../../src/base40.h: In function ‘std::__cxx11::string int_to_charset(uint64_t)’:
../../src/base40.h:53:10: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
  if (val < 0)  return "ERROR";
          ^
../../src/base40.h: At global scope:
../../src/base40.h:19:20: warning: ‘pszBase16’ defined but not used [-Wunused-variable]
 static const char* pszBase16 = "0123456789abcdef";
                    ^

**Comment by wellenreiter01** [comment]
Not an error, but a warning, that a function never will return with the string "ERROR"

**Comment by cqtenq** [comment]
https://github.com/FeatherCoin/Feathercoin/commit/31de18a9af359ee00273e68740e161e7c1a48c88

**Comment by wellenreiter01** [comment]
seems to be fixed by Lizhi's commit
