### ISSUE TITLE
Advanced feature Opennames

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#102]
[0.9.3.1] >>
Menu:  Advanced : Opennames

The layout of the form needs some more work to tidy it up. In particular the PublicKey Hash title is being covered by the entry field box.

Suggest moving the field below the title, as interim measure.

I've done some fixes for this, awaiting testing.

**Comment by FeatherCoin** [comment]
What branch you are talking about?
Can you put the branch at the beginning of the title in square brackets?

**Comment by wrapperband** [comment]
This work has been completed in 0.9.6 and can be signed off

**Comment by wellenreiter01** [comment]
So this issue can be closed?

**Comment by wellenreiter01** [comment]
Closed by wrapperband's request
