### ISSUE TITLE
[0.9.3.2]  version accepts any block version > 2

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#113]
Version 0.9.3.2 accepts any block version > 2.
This opens a door for malicious users to create a block with a randon block version number, whichnthen will lead to a fork of the block chain, as 0.9.3.2 clients will accept the block, while 0.8.7.x and 0.9.3.1 will reject the block.

**Comment by cqtenq** [comment]
0.8.7.x and 0.9.3.1 will be eliminated.  we can send alert message.

**Comment by wellenreiter01** [comment]
They are eliminated when all users have upgraded. We can't force users to upgrade, so we have to secure the client against  such a situation. 
It should be a small change only anyway: Replace 'if Version >=2' with 'if ((Version== 2) or (Version ==4))
just a one liner ;)

**Comment by wrapperband** [comment]
Part of documenting  "the total release procedure" is to bring people on board and warn them of changes, we have a number of updates to integrate it makes no sense to release that dev version, when we a proper 0.9.3.3. is virtually ready to go and could be published properly.

I am suffering extra support issues (possibly because of 0.9.3.2) when we should be spending effort setting up a 0.11 testnet, and working on getting the updates and testing of that  ....

**Comment by wellenreiter01** [comment]
The testnet must reflect the prodnet, so we need 0.8.7, 0.9.3 and 0.11 in the testnet

**Comment by cqtenq** [comment]
I think 0.9.3.2 accept block 2 and block 4 , but mine block 2 only . 0.11 mine block 4 only. so 0.9.3.2 is a bridge.  When the main pool is installed, we will broadcast the V4

**Comment by wrapperband** [comment]
@Lizhi this seems  to be causing a lot of extra work for no apparent reason and adding a LOT of potential problems. It is causing a lot of stress we don't need. Let's concentrate on updating 0.11 to 0.9.3.2 standards or above and give people a "reason to upgrade". 
Unfortunately, we have tried to make it go faster but the upgrade to 0.11 can only go at a certain speed and by taking this unnecessary step (of having a bridge) we are actually slowing it down.....

**Comment by wellenreiter01** [comment]
Fixed in 0.9.6  in main.cpp line 2941:
 if ((block.nVersion !=2)&&(block.nVersion !=4)) 
            {
            		LogPrintf("AcceptBlockHeader,incorrect block version=%d \n",block.nVersion);
                return(state.DoS(100, error("AcceptBlock() : incorrect block version")));
            }
