### ISSUE TITLE
int64_t  nInterval defined but not used compile error / warning

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#116]
It seems that nInterval was defined twice, as int and int_64?

main.cpp:1275:22: warning: ‘nInterval’ defined but not used [-Wunused-variable]
 static const int64_t nInterval = nTargetTimespan / nTargetSpacing;

The first case on line 1275 : 

Then from 1342 : 

   // 2016 blocks initial, 504 after the 1st, 126 after the 2nd hard fork, 15 after the 3rd hard fork
    int nInterval = nTargetTimespan / nTargetSpacing;

**Comment by wellenreiter01** [comment]
the definition on line 1275 is at global level, while the deinition at line 1342 is local to unsigned int GetNextWorkRequired()

**Comment by cqtenq** [comment]
I remove that var.

**Comment by wellenreiter01** [comment]
Typo fixed in code
