### ISSUE TITLE
0.9.3.2 - Stealth error messages : what do they mean, why so many?

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#118]
Test : Create stealth Address
Close Wallet
Start wallet from a terminal
Observe posted messages

over 100 times : message is given :
StealthSecret(): Q EC_POINT_bn2point failed

What does it mean? Is it an error?

------------ Similar error message in development ....

after my pool confirm a stealth transaction, but I find a problem , I can not receive coin.
I check logfile.
FindStealthTransactions show a error “StealthSecret failed” in wallet.cpp,

StealthSecret(sScan, vchEphemPK, it->spend_pubkey, sShared, pkExtracted)

StealthSecret show a error “StealthSecret(): Q EC_POINT_bn2point failed” in stealth.cpp

if (!(Q = EC_POINT_bn2point(ecgrp, bnQ, NULL, bnCtx))) 

my a stealth transaction on blockchain.
http://block.ftc-c.com/tx/137455e27de1c7b3302c3b0c462fb0d904a831339aebf468e6e85c224362f51b
Block number:556535

SX address f5QuGW2S8TvSqszejNxxTATHh4AgJC2VVvMf5Lc2tk6uR4k3F361kwM8oiLecHT4z4q7qmUgnUE47HsqpGX6uZnUghvgLN7iiSpeA7

**Comment by wrapperband** [comment]
Further information : 
Close down wallet after resync up to date. Start wallet from command line.
Open wallet and click on HELP SX Search,  

Message is shown numerous times in terminal : StealthSecret(): Q EC_POINT_bn2point failed

**Comment by cqtenq** [comment]
Because loop call , those informations are printed.
