### ISSUE TITLE
0.9.3.2  - Test result   --Transaction right click - Dropdown Ubuntu 16.04

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#119]
The right click dropdown menu on Transaction grid / Button

The option :   Show transaction total 

Failed to  show any results / output

**Comment by wrapperband** [comment]
Sign off : Not Fixed in 0.9.6 : Raise issue to test Show Transaction Total is correct in 0.11 or further versions.

**Comment by wellenreiter01** [comment]
I keep it open, as some entries on the context menu show no actions.
