### ISSUE TITLE
0.9.3.2 - Test result --Transaction right click - Dropdown Bitmessage - Ubuntu 16.04 

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#120]
0.9.3.2 - Test result --Transaction right click - Dropdown 

Bitmessage - nothing happens, Bitmessage client was open

**Comment by cqtenq** [comment]
You need compile another project, then copy it to feathercoin run directory.
https://github.com/cqtenq/PyBitmessage

**Comment by wrapperband** [comment]
Ok, I'll add a note in the guide to that effect.

**Comment by wellenreiter01** [comment]
The dropown menu basically checks for the pybitmessage binary in the standard program directories for the os and starts it. 
bitmessage/pybitmessage is not really integrated in the code

**Comment by wrapperband** [comment]
We might as well sign this off, the documentation has been improved in pushes AFB and I did to 0.9.3.2 and 0.9.6
We can check that Bitmessage works, or review it's inclusion entirely as part of the audit of Feathercoin 0.11 alpha, and the way forward from there.

**Comment by wellenreiter01** [comment]
seems to be a duplicate to #119 -> close
