### ISSUE TITLE
SX Search for Stealth address

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#123]
Help - SX Search :
When you search for a stealth address, the information given seems incorrect.

After a wait (while the search happens, button goes blue) a message pops up 

"Scan stealth transactions on Blockchain,Yes!!!"

No Stealth addresses were found for the wallet . Click OK and it exits : 

Text needs updating : scan complete SX coins found for wallet or not

**Comment by wrapperband** [comment]
I see the message is in the (Chineese) Translations : As an quick fix, can you change the text to say.

Completed Search for Stealth coins  

Additionally it could show from : XXXX to : XXXXXy

I assume a different message is displayed if Stealth addresses are found, in which case ADD to the message...

: None found.

The Search has NOT found the stealth coins I have sent to myself, (yet).
I was not able to mine coins using NSGminer to a stealth address

**Comment by wellenreiter01** [comment]
Wrapper, do you see a chance to implement the changes? you know best, where to look and modify the language files is not a big deal.

**Comment by wellenreiter01** [comment]
Fixed in 0.9.6

Text now says *xxx Stealth transactions found on Blockchain."*
