### ISSUE TITLE
0.9.3.2 - Test results - Stealth search  low to v. high causes creash

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#126]
A search for stealth coins failed with crash.

How to replicate : help - SX Stealth search, set low  556536, set high 10000000     

Start Feathercoin on the "Command Line"
message on command line start up : 
StealthSecret(): Q EC_POINT_bn2point failed
Segmentation fault (core dumped)

**Comment by aciddude** [comment]
I can confirm this happens in 0.9.3.1, 0.9.3.2, 0.9.3.6  on MacOS - I dont get the segfault but I do get  "Feathercoin-Qt (not responding)" in activity monitor. CPU usage is in the high 90% and threads used does go up and down.

**Comment by wellenreiter01** [comment]
fixed in 0.9.6
