### ISSUE TITLE
coins.cpp - CCoinsViewCache::GetPriority has an overflow bug from Litecoin/Bitcoin code

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#127]
Check this bug is pulled when it is / confirmed / corrected .......

 relaypriority calculation error #247

@maiiz
maiiz commented 9 hours ago • edited

i create this issue(bitcoin#8334) in bitcoin ,and this also effect litecoin

relaypriority calculation error
CCoinsViewCache::GetPriority has an overflow bug that affects the relaypriority calculation.
The way the arithmetic works in that function is

dResult += coins->vout[txin.prevout.n].nValue \* (nHeight-coins->nHeight); 
the nValue variable type is int64_t, and the int64_t max value is 9223372036854775807

for example

nValue value  is 40000000000000
(nHeight->coins - nHeight )value is 300000 
40000000000000 \* 300000 > 9223372036854775807 

so the dResult will be negative number!
and the AllowFree function will return False, and the high priority transaction with low fee will be reject by node with error insufficient priority!

I found this bug when I send a transaction with rpc api sendrawtransaction,i debug the source code find it.

**Comment by aciddude** [comment]
aciddude commit cfd3100 

Tested on MacOS Sierra

**Comment by wellenreiter01** [comment]
Solved in 0.9.6
