### ISSUE TITLE
ignored devs-(bugs enclosed)

### ISSUE THREAD

**Issue by JazzMaster** [FeatherCoin/Feathercoin#143]
Im a little teed off at the ignored changes proposed.
1- I was attempting --I lost my changes but they can be automated-- to change from BITCoin to Feather. This includes naming conventions, ICONS, etc. We are not BIT, not Satoshi and our code should reflect this.
(I can update this for .9, just dont have time rite this second. I asked for upload permissions and got sent in loops.)
I am aware some functions, like voting, however, merge from the master tree. It would be better just to implement the function, rather rewrite OUR code repeatedly as a result of "master Satoshi" code changes.

2- I have a few bug to go with #1 that didnt get in here for some reason.

wallets:
public key is too big and runs off the page
no QR codes, as if built without lib zebra crossing or libqrencode when printed.
Paper wallet is wide enough but too small. Without QR codes, impossible to read

exchanges:
(dont rely so much on others, failures)
we have half busted code here because people are dropping us and also not putting us back in places like shapeshift.io. take out/disable the option or demand we get put back in the exchange.

All I asked on the theme, and background (QT UI) was that we be consistent and PROFESSIONAL looking. As I said, I was working on this. Pick an ICON SET for everyone to USE and STICK WITH IT. The better we SELL, the more clients and traffic we generate.

Someone needs also to CLEAN UP the code and layout, in mind we are devving for DROID (still working this one out), and MULTIPLE OS and arch. It would behoove someone to (AT FTC website) post OUR packages ON OUR SITE. (this IS possible, even with WP). AGAIN. Ignored.

64 bit Linux seems missing, beggin for 32 bit depends that on 64 bit CANNOT exist. This forces 64 bitters to RECOMPILE, which until recently with .9 WAS NOT POSSIBLE.

ALSO:
messaging of sort that an update is out within the app would be nice. BTC HAD this feature.

**Comment by wellenreiter01** [comment]
First of all, which branch/coder version are you referring to?
I've problems to understand your comments, so let me comment on the points I understood:

- Messaging/warnings can be sent out so an update notification is build into the code.
  You can see it if you run a version 0.8.6, 0.9.0, or even 0.9.5
- 64 bit Linux binaries are available for 0.8.7.3 and 09.3.1 see http://software.opensuse.org/package/feathercoin
- we post links to the software repositories on the website, while the software repositories provide the installation packages for various Linux distributions. This has the advantage, that users receive automatic updates, once they installed the wallet according to this guide: http://forum.feathercoin.com/topic/8327/guide-how-to-install-feathercoin-wallet-binaries-on-ubuntu-and-debian-linux-ppa

Finally let me tell you, that I'm sorry that you lost your changes. I assume you improved the wallet's code and lost it. Unfortuntelly I didn't see any pull request from you so I don't know what you coded.

If you want to help coding, please fork the repository into your own workspace, do your changes on the a new branch, probably containing you name in the branch-ID  and create a pull request to the feathercoin git repository.

This way we can include the changes from different coders into the code and use Githubs code checks to avoid code comming from one developer  beeing reversed/overwritten by changes from another coder.

**Comment by wrapperband** [comment]
Hi Jazzmaster,

Some of those changes could be rejected. We have considered wither changing names from Bitcoin is a good idea, it generates a lot of unnecessary work, when future Forks are converted. It has already been considered, unless there is some other reason.

These issues need to be discussed in the Feathercoin development threads on the forum to gain some acceptance by other contributers.

http://forum.feathercoin.com/category/71/technical-development

I note your changes are still on you fork, so you could try and resubmit any that have been missed? I would be interested what the libzxing change, but we already have a million more important things that should be done, as part of the 0,9.6 release, so we don't need to be diverted unnecessarily.

**Comment by wrapperband** [comment]
I think we can sign this of.

No response from Jazz Master. We can review his comments make an issue for each point, in the build tests. I've made a list of the relevant points.

1.  Public key : Task Test Paper public key is too big and runs off the page
2.  The exchanges have been informed, the additional services in 0.9.x will be reviewed as part of 0.11.
3.  FTC already have a policy on Feathercoin specific software changes, it is also at the descretion of the contributer of the work.  But that will be reviewed further as part of the 0.11 testing/updating/release procedure, possibly to reduce FTC specific changes so Bitcoin updates can be pulled in more regularly and have intermediate test builds.

**Comment by aciddude** [comment]
Closing this.  Most of JazzMasters were addressed with the 0.9.6 release.
