### ISSUE TITLE
0.9.6 Enable "Forward" compability with protocol version 2 when using protocol version 4 

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#151]
Enable "Forward" compatibility with protocol version 2 when using protocol version 4 (databases) when FTC move to 0.11 and beyond.

A test to cover the Block 2 and 4 forward compatibility needs to be included in the test suite.

Without forward compatibility all wallets would have to be updated a the next hard fork. As they may have to be updated anyway, seems sensible to remove forward compatibility than risk it failing.

It must therefore, at least, have and pass a test suite test.

**Comment by wellenreiter01** [comment]
according to Lizhi 0.9.6 is accepting block version 2 and bock version4 while producing block version 2 blocks when used for mining already.

**Comment by wellenreiter01** [comment]
Verified and working for 0.9.x/0.1.x versions
