### ISSUE TITLE
Formatting error on MultiSig GUI page

### ISSUE THREAD

**Issue by AmDDJunkie** [FeatherCoin/Feathercoin#160]
This was seen on the Windows x64 version. Im currently unable to check MAC or Linux GUI.

On the MultiSig page, I think the 'b' in 'Total balance' should be a capital 'B'. Also there should be a space after the ':' and before the '0.00'. Same for Addresses:0.

It should read   "Total Balance: 0.00 FTC       Addresses: 0"

![image](https://cloud.githubusercontent.com/assets/10658822/22607146/949651fa-ea24-11e6-9dde-68353a06f155.png)

**Comment by FeatherCoin** [comment]
Thanks for the Info.

We will fix that in the next release

**Comment by aciddude** [comment]
Fixed. Tested on MacOS Sierra &  QT 5.8
