### ISSUE TITLE
Cause for Slow FTC install blockchain sync : Litecoin pcmesagstart test loop.

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#164]
As FTC share pcmesgstart with litecoin, a litecoin node can connect, and if the node has more blocks than the local node, it starts sending blocks, which are refused, but it  ends up in a loop.

Stop/start feathercoind solves the problem eventually when a ‘real’ ftc node connected first and sent blocks

**Comment by wellenreiter01** [comment]
This will be fixed in 0.11.x, as we move to a dedicated pchMessageStart string

**Comment by wellenreiter01** [comment]
Sync issues are fixed in 0.13
