### ISSUE TITLE
GetWork broken in 0.9.6 and 0.9.6.1

### ISSUE THREAD

**Issue by aciddude** [FeatherCoin/Feathercoin#166]
Solo Mining doesn't work on 0.9.6

**Comment by wrapperband** [comment]
This is a high priority to find if there is a problem (now before 0.11). Needs a test system with a miner to investigate debug messages? If something needs fixing, we can update feathercoind - which most miners self compile - without affecting all wallets.

**Comment by aciddude** [comment]
This was fixed in https://github.com/FeatherCoin/Feathercoin/commit/cea31da289d1f5ad0487dc080ccf130b8cef43f2

Thanks @Bushstar

**Comment by wellenreiter01** [comment]
Fixed
