### ISSUE TITLE
0.9.6.1 gui only shows overview pane

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#180]
The 0.9.6.1 gui starts normally and also synchronizes with the BC.
When trying to open any window using the tools bar (send /receive coins, transactions, reports, multisig )
nothing happens.

All actions from the menu bar (wallet, settings, advanced,help) work fine

**Comment by aciddude** [comment]
Can you post details of your build env and dep versions ?

**Comment by wellenreiter01** [comment]
It was either a cache problem, an environmen problem  or a left over library from an old compile, that didn't match anymore.
I deleted my local copy, cloned again and all is fine now.
