### ISSUE TITLE
Incorrect setting of minimum fee

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#181]
In at least one place (in main.cpp) - FTC custom settings are required because of block time and reward scaling of Bitcoin parameters.

Further, whilst reviewing an emergency change, comparison should be made with the Litecoin setting, to ensure the further scaling of coin reward is reflected in the minimum fees.

This is very important as it is currently  mode of failure of Bitcoin and we will be stuck with high fees till the next release.
0.8
/** Fees smaller than this (in satoshi) are considered zero fee (for transaction creation) */
int64 CTransaction::nMinTxFee = 2000000;
/** Fees smaller than this (in satoshi) are considered zero fee (for relaying) */
int64 CTransaction::nMinRelayTxFee = 2000000;

0.9
/** Fees smaller than this (in satoshi) are considered zero fee (for transaction creation) */
int64_t CTransaction::nMinTxFee = 1000000;  // Override with -mintxfee
/** Fees smaller than this (in satoshi) are considered zero fee (for relaying and mining) */
int64_t CTransaction::nMinRelayTxFee = 1000000;

-----

In 0.8 but not 0.9 main.cpp

  // Feathercoin
    // To limit dust spam, add nBaseFee for each output less than DUST_SOFT_LIMIT
    BOOST_FOREACH(const CTxOut& txout, vout)
        if (txout.nValue < DUST_SOFT_LIMIT)
            nMinFee += nBaseFee;

    // Raise the price as the block approaches full
if (nBlockSize != 1 && nNewBlockSize >= MAX_BLOCK_SIZE_GEN/2)

**Comment by Bushstar** [comment]
The issue with Bitcoin was that competition for the limited space was driving up the dynamic fees, however I agree with your sentiment that we need to take care not to have fees set too high. Currently our blocks have lots of space but people are paying roughly 0.02 FTC per TX, taking some examples from recent TXs this is working out to 2,000 bytes per TX. This has the potential to be more expensive then I believe we want to be. We can lower TX fees and keep the cost of a spam attack expensive.

To be on par with LTC's previous releases seems sensible and will decrease fees 10x, this will keep fees at less than a cent per TX as right now if the FTC and BTC market move up we could be looking at fees over a cent. Lowering fees in the next release will keep us competitive. LTC is lowering their fees further in their next release but their cost is much higher than us so their previous example for fees like in their 0.13 release would be a better example to follow.
