### ISSUE TITLE
0.11.x  Investigate wither libqrencode can be removed and use libzxing qrencode instead

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#193]
check removal of qrencode dependency in 0.11.x’ and flag it as enhancement

**Comment by wellenreiter01** [comment]
This is more to check a possibility to remove the dependency on libqrencode, as libzxing also has qrencode features

**Comment by FeatherCoin** [comment]
While qrencode is required to create crcodes, zxing is used to decode qrcodes

Replacing qrencode with zxing is not possible
