### ISSUE TITLE
0.11.x Test section broken

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#194]
When compiling tests, compiler errors occur.

Expample : 
`test/base58_tests.cpp:95:10: note:   no known conversion for argument 1 from ‘CStealthAddress’ to ‘const CNoDestination&’
`

compilation aborts

**Comment by aciddude** [comment]
With this pull
https://github.com/FeatherCoin/Feathercoin/pull/198

the test binary builds. We need to go over test data and why some of the tests fail.

**Comment by wellenreiter01** [comment]
Shouldn't the test data the same we have in 0.9.6.1?

**Comment by aciddude** [comment]
Some of the data gets generated into a few json files.  That data can be the same from 0.9.6.1 as far as I am aware but I can double check. 

During a build the json files get created...I want to see if they are generating FTC or BTC data first. 

There's some tests where the Data is more or less hard-coded in...check the PoW tests for example. 
Those are the ones we will need to review.
