### ISSUE TITLE
Wallet doesn't work on OSX older than 10.12

### ISSUE THREAD

**Issue by siemiatj** [FeatherCoin/Feathercoin#196]
I was trying to install your wallet app on El Capitan and I got the incompatible version error. Any chances for a build that would run on older systems as well ? I personally don't plan to upgrade to Sierra, TurboSierra, MegaTurboSierra in the near future.

**Comment by wrapperband** [comment]
Thanks for the update, we're looking at it.

**Comment by aciddude** [comment]
Hi @siemiatj - Please can you try now. I've uploaded a new DMG. 

Thanks.
