### ISSUE TITLE
making Feathercoin 0.9.6.1: ‘QJsonObject: No such file or directory’ (but there is)

### ISSUE THREAD

**Issue by dchmelik** [FeatherCoin/Feathercoin#223]
I'm trying this on current stable Slackware64 14.2, and make leads to [these](https://gist.github.com/dchmelik/724e215bb04ebcbae7f14ecce5ac759d) errors.

But, I do have QJsonObject.

d@cosmos:~/Feathercoin-0.9.6.1$ locate QJsonObject
/usr/include/qt5/QtCore/QJsonObject

I also have a lot of Qt (if I recall, these somehow work at the same time, but maybe there's something else I need to do in the case of have Qt4, Qt5.)

d@cosmos:~/Feathercoin-0.9.6.1$ ls /var/log/packages/qt*
/var/log/packages/qt-4.8.7-x86_64-4
/var/log/packages/qt5-5.7.1-x86_64-1alien
/var/log/packages/qtscriptgenerator-0.2.0-x86_64-2
/var/log/packages/qt-compat32-4.8.7-x86_64-4compat32
/var/log/packages/qt5-webkit-5.7.1-x86_64-1alien
/var/log/packages/qt-gstreamer-1.2.0-x86_64-5alien
/var/log/packages/qtruby-4.14.3-x86_64-4alien

The problem isn't missing ‘development’ packages, as there aren't ones named those on Slackware, since it's designed for development and all the packages have the additional files for that (not separated out like on all the later, not as strictly Unix-like, distributions.)

**Comment by TheCharlatan** [comment]
Have the same problem. I am building in the same environment that I am using to build bitcoin and several other cryptocoins. The configure script does not pick up anything missing.

**Comment by wellenreiter01** [comment]
No such file or directory is probably a header file not found.

Try to include the path the QJsonObject in the include path.
See CPPFLAGS section in the output of configure --help

**Comment by wellenreiter01** [comment]
Update: 
I was able to duplicate the problem.
Is it possible, that you have installed qt4 and qt5?
the configure script checks for qt4 first and sets the include parameters accordingly.
qt4 has no QJsonbject.

please try to run configure with --with-gui=qt5

**Comment by dchmelik** [comment]
Ok, after your instructions, I no longer get that error... but in lines after, I got many/tens pages of new errors... I'll post those when I can.
