### ISSUE TITLE
many make errors (I have Qt4 & Qt5)

### ISSUE THREAD

**Issue by dchmelik** [FeatherCoin/Feathercoin#232]
For Feathercoin 0.9.6.1, I get tens of pages of make errors: [log](https://gist.github.com/dchmelik/7b84cfd6b8cfb8dfd143ed1b33bbcacc).  As I had said from the beginning in [issue #223](https://github.com/FeatherCoin/Feathercoin/issues/223), I have Qt4, Qt5.  My GNU/Linux  distribution officially has Qt4, but one of the programmers/engineers releases software to test with Qt5, which I now use (main GUI.)  I don't know if having both is the issue, or what should be done.  Later I'll probably even reinstall software with Qt3, all these at once, and maybe try something with Qt1, etc.

**Comment by aciddude** [comment]
Hi @dchmelik  

Thanks for logging this issue.  You can see in your error log that: 
`error "Qt requires C++11 support"`

depending on how you're builing  (with make or qmake) you need to set some CXXFLAGS or QMAKE_CXXFLAGS in your environment table before you build the Feathercoin Wallet. 

look at my configure command for MacOS 

` ./configure --disable-upnp-default --disable-tests --without-miniupnpc LDFLAGS="-L/usr/local/opt/berkeley-db4/lib/ -L/usr/local/opt/qrencode/lib/" CPPFLAGS=" -I/usr/local/opt/berkeley-db4/include/ -I/usr/local/opt/qrencode/include/" CXXFLAGS="-arch x86_64 -std=c++11 -stdlib=libc++" --with-gui=qt5 --with-qrcode=yes
`

the part that matters to you is this: 

`CXXFLAGS="-arch x86_64 -std=c++11 -stdlib=libc++" `

Hope this helps.

**Comment by dchmelik** [comment]
Okay, I did that (plus stuff people/you said for my last couple issues/questions.)  Now it won't even get through [configure](https://gist.github.com/dchmelik/b424c843b748c292d3341ade2d843a84);  ‘configure: error: "Big Endian not supported."'  Maybe something instructed above is more for MacOS?

**Comment by wellenreiter01** [comment]
This should be solved in 0.9.6.2
the wallet builds on qt4 and qt5 now.
