### ISSUE TITLE
[0.9.x] RPC dumpwallet issue empty content

### ISSUE THREAD

**Issue by looarn** [FeatherCoin/Feathercoin#236]
Tested on 0.9.3.2 and on last 0.9.6.1.

## Reproduce
+ Launch Feathercoin Core Wallet
+ Open the RPC console
+ Try to dump your wallet `dumpwallet my_dumped_wallet_file`

## Expected result
The file should list all addresses and their related private keys + the masterkey of the wallet.

## Actual result
```
# Wallet dump created by Bitcoin v0.9.6.1-ftcit-Standard (2017-07-08 08:10:56 +0200)
# * Created on 2017-09-25T02:25:20Z
# * Best block at time of backup was 1897402 (6ad9558e6175774fd25f7d6ff06a0e383dda52b7a90c394341d391fe3a247d2c),
#   mined on 2017-09-25T02:23:13Z


# End of dump
```
The dump content is empty.

Tested on Windows 7 64bits.

**Comment by aciddude** [comment]
Fixed in https://github.com/FeatherCoin/Feathercoin/commit/6aae917096a963c2142874ea57168b17e895547f
