### ISSUE TITLE
Feathercoin-QT crashes on Mac OSX 10.9.5

### ISSUE THREAD

**Issue by legojesus** [FeatherCoin/Feathercoin#253]
Just got the latest version, opening the program, nothing happens for about 30 seconds and then crash. 

I have attached the crash log here. 
[Feathercoin-Qt_2017-11-28-164557.txt](https://github.com/FeatherCoin/Feathercoin/files/1510334/Feathercoin-Qt_2017-11-28-164557.txt)

**Comment by aciddude** [comment]
You are on osx 10.9.5. How old is your mac  ?

**Comment by legojesus** [comment]
It's a late 2011 Macbook Pro. Staying on 10.9.5 for legacy projects at work. 
Also, I really dislike 10.10 and above :P

**Comment by aciddude** [comment]
Ok. That sounds fair. I'll try to upload a new DMG that will work with versions that far back.  Won't be today though.

**Comment by legojesus** [comment]
No problem. Working on an older wallet for now.

**Comment by DJSymBiotiX** [comment]
Similarly I'm on OSX 10.11.6 and I can't even open the app because it's telling me I need at least 10.12

**Comment by Querzel** [comment]
+ 1 ... Using Mac OSX 10.10., won't start and asks for at least OSX 10.12. Thanks for new DMG

**Comment by aciddude** [comment]
Running MacOS 10.10  works with Feathercoin 0.13
