### ISSUE TITLE
feathercoin-cli not showing all accounts

### ISSUE THREAD

**Issue by Phlosen** [FeatherCoin/Feathercoin#255]
I confess: I am Noob and maybe did somethings wrong. But this is what issue I had:

I set up an Ubuntu Server 16.04 and compiled the current feathercoincore from here. Got the daemon running etc. However, I created another account in the wallet. After listaccounts I saw two accounts like:

"": 0.0000
"account1":000000

all good so far. I dumped the public keys for the accounts and the privates to write down... More out of curiosity than anything else.

Later I managed to get x11 working and started to feathercoin-qt. I saw the two accounts (same public) but there where two more accounts with "" and one more with "account1". They had different publics. I renamed them in the GUI, went back to cli and did a listaccounts. Saw them all, no Problem.

I think i falsely created these accounts with the same account name. The cli seems to only see the first account with the Name.

**Comment by wellenreiter01** [comment]
There should be a check, that prevents creating an account, if an account with the same name already exists.

**Comment by Bushstar** [comment]
I'm closing this issue as it is now five months old and is possibly misinterpreted on the user's end, no offence meant. Accounts will be deprecated in the 0.18 release.
