### ISSUE TITLE
Feathercoin-qt crashes on MAC High Sierra OS X 10.13.2 

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#258]
Feathercoin-qt crashes on MAC High Sierra OS X 10.13.2 

OS Version: Mac OS X 10.13.2 (17C88)

Possible Solution
https://github.com/bitcoin/bitcoin/issues/12009

**Comment by Bushstar** [comment]
The issue linked by Wrapper was fixed in 0.15 and will not be an issue in the 0.16 Mac release. If there's a particular issue outstanding create a new issue with debug.log and any other relevant OS logs.
