### ISSUE TITLE
Feathercoin icon redesign :  The icons in 0.13.x are higher resolution than 0.9.6.x.

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#261]
Feathercoin icon redesign :  The icons in 0.13.x are higher resolution than 0.9.6.x.
0.13.x    Needs a review of FTC icons and higher resolution  versions produced of the 0.9.6.x icons, particularly - connection, spinner ....

0.13 connection icon is 92 x 92
The 0.9 icon is 72 x 72
Most of the 0.13 icons are bigger.
Probably for high DPI screens.

**Comment by natedavis** [comment]
If we want to change the icon we sure can. I had a designer buddy of mine work through some mockups of a new Feathercoin Logo. We can use these, of if not, I can get the older one scaled and figured out how to get the sizes we need. Anyway, here is just some ideas...

[Feathercoin2.pdf](https://github.com/FeatherCoin/Feathercoin/files/1656944/Feathercoin2.pdf)

**Comment by Bushstar** [comment]
Wrapper is mostly referring to the icon set for various menus and other locatiosn in the GUI client, the previous icon set in 0.9 is too small for 0.13's requirements.

**0.9**
https://github.com/FeatherCoin/Feathercoin/tree/master-0.9/src/qt/res/icons

**0.13**
https://github.com/FeatherCoin/Feathercoin/tree/master-0.13/src/qt/res/icons

**Comment by Querzel** [comment]
Why do we keep the logo named bitcoin.png and not change it to feathercoin.png etc.? 
Won't that cause the following error again? https://github.com/FeatherCoin/Feathercoin/issues/204
In Litecoin they keep the name bitcoin.png too... hmhm
https://github.com/litecoin-project/litecoin/tree/master/src/qt/res/icons 
Just trying to avoid future sources of problems :)

**Comment by Bushstar** [comment]
It will not cause an error as the code still refers to bitcoin.png. There are many variables and files that have Bitcoin in them and there's no benefit to changing them unless they are displayed in some way to the use in the compile binary.

**Comment by Bushstar** [comment]
Thanks to @wrapperband for providing updated icons for use in Feathercoin.
