### ISSUE TITLE
v0.9.6.2 (64bit) Mac OSX 10.10.5 - Exception: St12out_of_range

### ISSUE THREAD

**Issue by Querzel** [FeatherCoin/Feathercoin#266]
Hey,
I get the following exception several times, is this a known issue ? 

************************
EXCEPTION: St12out_of_range
CInv::GetCommand() : type=1073741826 unknown type
feathercoin in ProcessMessages()

Can I provide more infos ? 

The Client eats up more RAM than Bitcoin-QT and Litecoin-QT ... 
And there is no significant Mempool.

Besides that, the client is running just fine.

**Comment by wrapperband** [comment]
Litecoin increased their mempool size in code. Can you give figures on memory to see how significant?

**Comment by Querzel** [comment]
FTC: 840 MB
LTC: 684 MB
BTC: 567 MB

Running since 15 h, fully synced. 
Size of DB cache 1024 MB under preferences.
Number of connections: 15 (In: 5 / Out: 10)

Will be optimized in 0.13 I think ... 
I just thought there is a connection to the exception.

**Comment by Querzel** [comment]
Fixed in 0.13
