### ISSUE TITLE
V0.13  Transaction window doesn't show totals beneath the list of tranactions.

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#270]
v0.9.x showed a total of coins received at the bottom of the GUI's transaction view.
v0.13 is missing that feature.

This feature is useful to get the number of coind received for a given time span (day, week, last week, last month,...)

**Comment by Bushstar** [comment]
I think that was a Lizhi hand rolled feature. Currently we are keeping the GUI as vanilla as possible to ease porting to new versions of Bitcoin when it is released.
