### ISSUE TITLE
I encountered a compilation error at  hash.cpp

### ISSUE THREAD

**Issue by cqtenq** [FeatherCoin/Feathercoin#276]
cd /C/Coin/FTC/ftc-0.13

cd depends
make HOST=i686-w64-mingw32
cd ..

./autogen.sh

CPPFLAGS="-I/C/Coin/BaseLib/db-4.8.30.NC/build_unix \
-I/C/Coin/BaseLib/boost_1_58_0 \
-I/C/Coin/BaseLib/ZebraCrossing-master/src/libsrc \
-I/C/Coin/BaseLib/libevent-2.0.12-stable/include \
-I/C/Coin/BaseLib/openssl-1.0.2n/include \
-I/C/Coin/BaseLib \
-I/C/Coin/BaseLib/protobuf-2.6.1/src \
-I/C/Coin/BaseLib/libpng-1.6.16 \
-I/C/Coin/BaseLib/qrencode-3.4.4 \
-I/C/Coin/BaseLib/gmp-6.0.0 " \
LDFLAGS="-L/C/Coin/BaseLib/db-4.8.30.NC/build_unix \
-L/C/Coin/BaseLib/boost_1_58_0/stage/lib \
-L/C/Coin/BaseLib/ZebraCrossing-master/mw \
-L/C/Coin/BaseLib/libevent-2.0.12-stable/.libs \
-L/C/Coin/BaseLib/openssl-1.0.2n \
-L/C/Coin/BaseLib/miniupnpc-1.9 \
-L/C/Coin/BaseLib/protobuf-2.6.1/src/.libs \
-L/C/Coin/BaseLib/libpng-1.6.16/.libs \
-L/C/Coin/BaseLib/qrencode-3.4.4/.libs \
-L/C/Coin/BaseLib/gmp-6.0.0/.libs" \
BOOST_ROOT=/C/Coin/BaseLib/boost_1_58_0 \
./configure \
 --prefix=$PWD/depends/i686-w64-mingw32 \
--disable-upnp-default \
--disable-tests \
--enable-asm \
--enable-static \
--with-gui=qt5 \
--with-qt-incdir=/C/QT/5.3.2/include \
--with-qt-libdir=/C/QT/5.3.2/lib \
--with-qt-plugindir=/C/QT/5.3.2/plugins \
--with-qt-bindir=/C/QT/5.3.2/bin \
--with-boost=/C/Coin/BaseLib/boost_1_58_0 \
--with-boost-system=mgw49-mt-s-1_58 \
--with-boost-filesystem=mgw49-mt-s-1_58 \
--with-boost-program-options=mgw49-mt-s-1_58 \
--with-boost-thread=mgw49-mt-s-1_58 \
--with-boost-chrono=mgw49-mt-s-1_58 \
--with-protoc-bindir=/C/Coin/BaseLib/protobuf-2.6.1/src \
--with-boost=/C/Coin/BaseLib/boost_1_58_0/stage \
--with-boost-libdir=/C/Coin/BaseLib/boost_1_58_0/stage/lib

make  HOST=i686-w64-mingw32

make[3]: Leaving directory `/C/Coin/FTC/ftc-0.13/src/secp256k1'
  CXXLD  libbitcoinconsensus.la
.libs/libbitcoinconsensus_la-hash.o: In function `Z16HMAC_SHA512_InitP15HMAC_SHA512_CTXPKvj':
c:\Coin\FTC\ftc-0.13\src/hash.cpp:223: undefined reference to `SHA512_Init'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:224: undefined reference to `SHA512_Update'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:225: undefined reference to `SHA512_Final'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:231: undefined reference to `SHA512_Init'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:232: undefined reference to `SHA512_Update'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:236: undefined reference to `SHA512_Init'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:237: undefined reference to `SHA512_Update'
.libs/libbitcoinconsensus_la-hash.o: In function `Z17HMAC_SHA512_FinalPhP15HMAC_SHA512_CTX':
c:\Coin\FTC\ftc-0.13\src/hash.cpp:248: undefined reference to `SHA512_Final'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:249: undefined reference to `SHA512_Update'
c:\Coin\FTC\ftc-0.13\src/hash.cpp:250: undefined reference to `SHA512_Final'
.libs/libbitcoinconsensus_la-hash.o: In function `Z18HMAC_SHA512_UpdateP15HMAC_SHA512_CTXPKvj':
c:\Coin\FTC\ftc-0.13\src/hash.cpp:242: undefined reference to `SHA512_Update'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [libbitcoinconsensus.la] Error 1

**Comment by cqtenq** [comment]
I can compile bitcoin 0.13 succeful, but feathercoin 0.13 error . There may be some omissions .

**Comment by cqtenq** [comment]
OK , I see Bushstar's back on HTMLCoin,  the --enable-static  and --disable-shared  must been set.
It's working.

**Comment by wellenreiter01** [comment]
_--enable-static and --disable-shared_ must been set for windows compiles only
