### ISSUE TITLE
When compiled with zmq support daemon exits with assert error

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#280]
When zmq support is enabled, the daemon exits with an assert error. 
The error is casued by a problem to interpret the zmq configuration parameter.

The daemon only works if either
 - all 4 possible zmq interfaces are configured as first parameters in feathercoin.com
or
- all 4 possible zmq paramter are given as the first 4 parameter on the command line when starting the daemon

The problem seems to be in zmq/zmqnotificationinterface.cpp line 43/44

**Comment by wrapperband** [comment]
Some notes on zmq.

By default, the ZeroMQ feature is automatically compiled in if the necessary prerequisites are found. To disable, use --disable-zmq during the configure step of building bitcoind:

$ ./configure --disable-zmq (other options)

Block and Transaction Broadcasting with ZeroMQ

ZeroMQ is a lightweight wrapper around TCP connections, inter-process communication, and shared-memory, providing various message-oriented semantics such as publish/subscribe, request/reply, and push/pull.

The Bitcoin Core daemon can be configured to act as a trusted "border router", implementing the bitcoin wire protocol and relay, making consensus decisions, maintaining the local blockchain database, broadcasting locally generated transactions into the network, and providing a queryable RPC interface to interact on a polled basis for requesting blockchain related data. However, there exists only a limited service to notify external software of events like the arrival of new blocks or transactions.

https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md

**Comment by wellenreiter01** [comment]
Solved
