### ISSUE TITLE
Cyrillic alphabet translations of Feathercoin - Биткоин (Bitkoin)

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#291]
Биткоин   stands for Bitkoin in cyrillic alphabet  kyrgyz.

Translations are only for English.  https://github.com/FeatherCoin/Feathercoin/search?utf8=%E2%9C%93&q=%D0%91%D0%B8%D1%82%D0%BA%D0%BE%D0%B8%D0%BD&type=

канат  Feather
тыйын  Coin

тыйын Koin

**Comment by Bushstar** [comment]
канат translates to rope for me. There is a bigger issue here that we need native speaks of each language in the locale directory to work on the translations.

**Comment by wellenreiter01** [comment]
Do we still have issues with translations?

**Comment by Bushstar** [comment]
@wellenreiter01 basically yes, translations are best guess, but we'd need native speakers to translate each locale properly.
