### ISSUE TITLE
remove Bitcoin related release notes

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#293]
There are old Bitcoin related release notes in the docs directory.

We should provide Feathercoin release notes only.

**Comment by lclc** [comment]
I would not do this as the Bitcoin release notes are very much related to the Feathercoin releases.

**Comment by wellenreiter01** [comment]
I'm talking about old release notes from versions where Feathercoin was a fork of Litecoin.
Also in actual release notes we at leas t should change every occurrence of 'Bitcoin' or 'bitcoin to 'Feathercoin'.

Looks not professional to have release notes mention another coin
