### ISSUE TITLE
what's going on with the network?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [FeatherCoin/Feathercoin#360]
https://chainz.cryptoid.info/ftc/ - it has a lot of blocks in a batches and some big gaps like i saw a gap of more then one hour.

**Comment by aciddude** [comment]
This is just bad actors trying to mess with the network.  The team is working on a fix for eHRC which will sort out these issues with block times. 

it happens because large hashrate joins the network and then leaves but the diff remains high for too long

**Comment by FuzzyBearBTC** [comment]
the concern is the large hashrate person could 51% attack if they wanted...

**Comment by aciddude** [comment]
@FuzzyBearBTC  - actually this is not possible with Feathercoin because we have Checkpointing.  So they could only try to 51% attack  5 blocks back at the most...

**Comment by FuzzyBearBTC** [comment]
@aciddude  checkpoints only prevent the past history of blocks, agreed a 51% attack could only rewrite back the last 5 blocks to the last hard coded checkpoint.... however all the new blocks that are generated are open for attack see https://bitcoin.stackexchange.com/questions/67713/51-attack-and-rewriting-to-the-latest-checkpoint. Merge mining was devcoin/namecoin/i0coin/ixcoin solution to using the same hashing algorithm as btc but never going to have the same hashrate supporting each coin for security.. maybe that would be something useful for scrypt coins if feathercoin could be mined alongside Litecoin for example?

**Comment by wellenreiter01** [comment]
Gentlemen, as this extends from an issue discussion and how to fix the issue to a borader discussion, how Checkpointing is handled in the latest versions of the client, can we move the discussion to https://forum.feathercoin.com, please?
