### ISSUE TITLE
Compilation 

### ISSUE THREAD

**Issue by pinpins** [FeatherCoin/Feathercoin#364]
Hello,

Ubuntu 16

To reproduce:
./autogen.sh
 ./configure CFLAGS=-fPIC CXXFLAGS=-fPIC --enable-shared --without-gui --disable-tests
make

Error:
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/home/pool/Feathercoin/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
/usr/bin/ld: crypto/.libs/libbitcoinconsensus_la-neoscrypt_asm.o: relocation R_X86_64_PC32 against symbol `blake2s_compress' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

**Comment by Bushstar** [comment]
You've got --enable-shared set. Do the following and run make clean then make.

./configure --disable-shared --enable-static

**Comment by wellenreiter01** [comment]
--enable-shared with the above mentioned exports works, too ;)

**Comment by pinpins** [comment]
Please add it to instructions then at least

**Comment by Bushstar** [comment]
--disable-shared --enable-static should no longer be required in the 0.17 branch and any other future branches.
