### ISSUE TITLE
https://feathercoin.com/ old wallet version for download

### ISSUE THREAD

**Issue by douglasdeodato** [FeatherCoin/Feathercoin#376]
at the website after click in the link download/windows:  the user downloads the old version: v0.17.0
@Bushstar Bushstar released this on 26 Oct 2018 

can you guys update the link over there?

thanks.

**Comment by Bushstar** [comment]
Links have now been updated to 0.18.1 though I think this request is old and was asking to update to the 0.17.0.1 release.
