### ISSUE TITLE
error : assertion failed expression: pindexWalk -> pprev

### ISSUE THREAD

**Issue by douglasdeodato** [FeatherCoin/Feathercoin#377]
I am using : **windows 10 pro 64bits**  and **feathercoin-0.17.0.2-win64**

**error : assertion failed expression: pindexWalk -> pprev
file: chaib.cppm line 102**

am i missing any c++ library or something?

![ftc](https://user-images.githubusercontent.com/993318/55772258-e3b30a80-5a61-11e9-8848-97dc75528959.png)

**Comment by Bushstar** [comment]
Restart the client, if that fails delete everything in the data directory except for the wallet.dat or wallets subdirectory.

**Comment by douglasdeodato** [comment]
Hi @Bushstar, I have tried everything what you said before open this issue,  I solved deleting my whole blockchain data which I sync till jun 2018, so I have to download it again from scratch was the only way to make the wallet software to open.

thanks for the reply
