### ISSUE TITLE
wallet stops syncing if checkpoint orphaned

### ISSUE THREAD

**Issue by cipig** [FeatherCoin/Feathercoin#384]
all my wallets stopped syncing
```
2020-01-20T19:15:25Z ERROR: ProcessNewBlock: AcceptBlock FAILED ( (code 0))
2020-01-20T19:15:25Z ERROR: AcceptBlock: rejected by synchronized checkpoint
```
reason:
`2020-01-20T19:14:02Z LoadBlockIndexDB(): synchronized checkpoint 3e31786265b00985cdf59774db7b11124eadb5de8c50dbf343a498833501f12e`
which is a orphaned block: http://explorer.feathercoin.com/block/3e31786265b00985cdf59774db7b11124eadb5de8c50dbf343a498833501f12e

btw, how can i disable the checkpointing stuff?

**Comment by Bushstar** [comment]
I'm creating an updated version of Feathercoin now and will push the code changes as soon as possible.

**Comment by Bushstar** [comment]
@cipig 0.18.2 update is available from below, ACP needs some testing and I'll add something to allow skipping of it entirely for circumstances like this.

https://github.com/FeatherCoin/Feathercoin/releases/tag/v0.18.2

**Comment by Bushstar** [comment]
@cipig 0.18.2 update is available from below, ACP needs some testing and I'll add something to allow skipping of it entirely for circumstances like this.

https://github.com/FeatherCoin/Feathercoin/releases/tag/v0.18.2

**Comment by cipig** [comment]
Thanks for the quick fix. Wallets are working again after updating to latest master.
