### ISSUE TITLE
Wrong checksum ?

### ISSUE THREAD

**Issue by g574** [FeatherCoin/Feathercoin#387]
It seems like the 0.18.3 checksum file contains a wrong checksum for `feathercoin-0.18.3-linux64.tar.gz`.

Expected behavior: matching checksum

Actual behavior: checksum mismatch.

I tried 3 times, it was the same result
Steps to reproduce:
- download the [checksum file](https://github.com/FeatherCoin/Feathercoin/releases/download/v0.18.3/SHA256SUMS.asc)
- download the [tar file](https://github.com/FeatherCoin/Feathercoin/releases/download/v0.18.3/feathercoin-0.18.3-linux64.tar.gz)
- check code in file:
```
grep feathercoin-0.18.3-linux64.tar.gz SHA256SUMS.asc
67abdf2f581d09fb3ceda52a05b374781393dfb166e131874d0e4fb8174c4e1d  feathercoin-0.18.3-linux64.tar.gz
```
- calculate checksum of the tar file:
```
sha256sum feathercoin-0.18.3-linux64.tar.gz
219cd173bd2b466de78c8b561c1530f4d74001157e6a2cfc427f97e4eda3ed21  feathercoin-0.18.3-linux64.tar.gz
```

Version:0.18.3

**Comment by Bushstar** [comment]
Thanks for the report. I've uploaded the 0.18.3 files again and tested that the Linux 64bit archive now produces the result expected.

**Comment by g574** [comment]
Thank you very much. Problem solved.
