### ISSUE TITLE
0.18.3 defaults to testnet?

### ISSUE THREAD

**Issue by Austpool** [FeatherCoin/Feathercoin#390]
Does 0.18.3 default to testnet even if main net is set?

It seems to have wasted all mining since released....

I had mined a lot of blocks. I had 6+ peers connected. 
Testnet showed as false when i call getinfo ( using depreciated accounts)
 dropped back to 0.18.2 and it connected correctly to the rest of the world. even though it showed connected correctly before on 18.3...

**Comment by wellenreiter01** [comment]
No, 18.3 connects to the main net correctly.
Did you use a pool, especially one of the p2pool nodes?

**Comment by Austpool** [comment]
i had it under yiimp. it mined fine. i had 6 connections at any one time. wallet said balance was good. blocks sync fully. showed block finds as proven. everything looked fine. external miners could mine fine, but yiimp never sent the coins to their wallet. however, it said payments were made just fine on admin panel. everything looked great. difficulty was reset as stated and would grow harder as it found blocks. i could send coins via the CLI and got a transaction hash. coins never made it to their destination.  
I could not fault it otherwise, but block finds did not match the explorer.... 
i even shut the daemon down and did a reindex when i was suss about it. still came up fine.

but, deleted everything in the "." folder except the wallet data and started 18.2 instead. now working perfectly. ( i believe....)

**Comment by Austpool** [comment]
ok, so i now have a found block since replacing 18.3 with 18.2 and downloading the block chain again.  Did not change my config on yiimp or my conf file in any way.
block is showing on explorer.
so all fixed and working, but waste a lot of time on 18.3. 
cheers
