### ISSUE TITLE
make halts because a type/class doesn't have BOOST_FILESYSTEM_C_STR in boost 1.80.0

### ISSUE THREAD

**Issue by dchmelik** [FeatherCoin/Feathercoin#397]
Feathercoin 0.19.1.1 doesn't compile with boost-1.80.0-x86_64-2 (Slackware64 15+current GNU/Linux).

Make always terminates with warnings/errors such as a type/class doesn't have BOOST_FILESYSTEM_C_STR: [gist](https://gist.github.com/dchmelik/4b30c2209e31acc21a5a667a0eaef9fe) (or likely the definition changed/.moved).

**Comment by wellenreiter01** [comment]
I have no experience with slacware, but on an OpenSuSE system libbost_filesystem is not part of the libboot package.
Here is a list of requirements, as I see it:

BuildRequires: libminiupnpc-devel
BuildRequires: libQt5Core-devel libQt5Gui-devel libQt5Network-devel libQt5Widgets-devel 
BuildRequires: libQt5PrintSupport-devel libqt5-qtbase-devel  libqt5-linguist  
BuildRequires: db-devel
BuildRequires: update-desktop-files 
BuildRequires:  boost-devel libboost_system-devel libboost_filesystem-devel
BuildRequires:  libboost_program_options-devel libboost_thread-devel gcc-c++ 
BuildRequires: 	protobuf-devel libevent-devel
BuildRequires:	qrencode-devel libopenssl-1_0_0-devel

qr-encode is needed only, if qrcode ist enables in configure

**Comment by Bushstar** [comment]
Use the dependencies provided in the depends folder.

https://github.com/FeatherCoin/Feathercoin/tree/master/depends

**Comment by dchmelik** [comment]
okay; built on an alternative OS
