### ISSUE TITLE
Custom includes/libs not given high enough priority causing compile/link errors

### ISSUE THREAD

**Issue by githubuser404** [FeatherCoin/Feathercoin#48]
# Problem: system libs are included before custom libs causing compile/link errors

# git clone https://github.com/FeatherCoin/Feathercoin.git

# qmake "USE_UPNP=-" "USE_QRCODE=1" "BOOST_INCLUDE_PATH=/usr/local/boost-1.55.0/include" "BOOST_LIB_PATH=/usr/local/boost-1.55.0/lib" "OPENSSL_INCLUDE_PATH=/usr/local/openssl-1.0.1h/include" "OPENSSL_LIB_PATH=/usr/local/openssl-1.0.1h/lib" "BDB_INCLUDE_PATH=/usr/local/db-5.1.29.NC/include" "BDB_LIB_PATH=/usr/local/db-5.1.29.NC/lib" "QRENCODE_INCLUDE_PATH=/usr/local/qrencode-3.4.3/include" "QRENCODE_LIB_PATH=/usr/local/qrencode-3.4.3/lib

# make
...
...
g++ -c -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2 -D_REENTRANT -fdiagnostics-show-option -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -Wstack-protector -DQT_GUI -DBOOST_THREAD_USE_LIB -DBOOST_SPIRIT_THREADSAFE -DUSE_QRCODE -DUSE_IPV6=1 -DHAVE_BUILD_INFO -DLINUX -D_FILE_OFFSET_BITS=64 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Isrc/json -Isrc/qt -Isrc/leveldb/include -Isrc/leveldb/helpers -I/usr/local/boost-1.55.0/include -I/usr/local/db-5.1.29.NC/include -I/usr/local/openssl-1.0.1h/include -I/usr/local/qrencode-3.4.3/include -Ibuild -Ibuild -o build/qrc_bitcoin.o qrc_bitcoin.cpp
g++ -fstack-protector-all -Wl,-O1 -o feathercoin-qt build/bitcoin.o build/bitcoingui.o build/transactiontablemodel.o build/addresstablemodel.o build/optionsdialog.o build/sendcoinsdialog.o build/coincontroldialog.o build/coincontroltreewidget.o build/addressbookpage.o build/signverifymessagedialog.o build/aboutdialog.o build/editaddressdialog.o build/bitcoinaddressvalidator.o build/alert.o build/version.o build/sync.o build/util.o build/hash.o build/netbase.o build/key.o build/script.o build/main.o build/init.o build/net.o build/bloom.o build/checkpoints.o build/addrman.o build/db.o build/walletdb.o build/clientmodel.o build/guiutil.o build/transactionrecord.o build/optionsmodel.o build/monitoreddatamapper.o build/transactiondesc.o build/transactiondescdialog.o build/bitcoinstrings.o build/bitcoinamountfield.o build/wallet.o build/keystore.o build/transactionfilterproxy.o build/transactionview.o build/walletmodel.o build/walletview.o build/walletstack.o build/walletframe.o build/bitcoinrpc.o build/rpcdump.o build/rpcnet.o build/rpcmining.o build/rpcwallet.o build/rpcblockchain.o build/rpcrawtransaction.o build/overviewpage.o build/csvmodelwriter.o build/crypter.o build/sendcoinsentry.o build/qvalidatedlineedit.o build/bitcoinunits.o build/qvaluecombobox.o build/askpassphrasedialog.o build/protocol.o build/notificator.o build/paymentserver.o build/rpcconsole.o build/scrypt.o build/noui.o build/leveldb.o build/txdb.o build/splashscreen.o build/checkpointsync.o build/qrcodedialog.o build/moc_bitcoingui.o build/moc_transactiontablemodel.o build/moc_addresstablemodel.o build/moc_optionsdialog.o build/moc_sendcoinsdialog.o build/moc_coincontroldialog.o build/moc_coincontroltreewidget.o build/moc_addressbookpage.o build/moc_signverifymessagedialog.o build/moc_aboutdialog.o build/moc_editaddressdialog.o build/moc_bitcoinaddressvalidator.o build/moc_clientmodel.o build/moc_guiutil.o build/moc_optionsmodel.o build/moc_monitoreddatamapper.o build/moc_transactiondesc.o build/moc_transactiondescdialog.o build/moc_bitcoinamountfield.o build/moc_transactionfilterproxy.o build/moc_transactionview.o build/moc_walletmodel.o build/moc_walletview.o build/moc_walletstack.o build/moc_walletframe.o build/moc_overviewpage.o build/moc_csvmodelwriter.o build/moc_sendcoinsentry.o build/moc_qvalidatedlineedit.o build/moc_bitcoinunits.o build/moc_qvaluecombobox.o build/moc_askpassphrasedialog.o build/moc_notificator.o build/moc_paymentserver.o build/moc_rpcconsole.o build/moc_macnotificationhandler.o build/moc_splashscreen.o build/moc_qrcodedialog.o build/qrc_bitcoin.o    -L/usr/lib -lqrencode /root/Feathercoin/src/leveldb/libleveldb.a /root/Feathercoin/src/leveldb/libmemenv.a -lrt -L/usr/local/boost-1.55.0/lib -L/usr/local/db-5.1.29.NC/lib -L/usr/local/openssl-1.0.1h/lib -L/usr/local/qrencode-3.4.3/lib -lssl -lcrypto -ldb_cxx -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lpthread -lQtGui -lQtNetwork -lQtCore 
build/bitcoinrpc.o: In function `boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0xa9): undefined reference to `TLSv1_2_client_method'
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0xe9): undefined reference to `TLSv1_2_server_method'
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0x1c1): undefined reference to `TLSv1_1_method'
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0x1d1): undefined reference to `TLSv1_1_client_method'
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0x1e1): undefined reference to `TLSv1_1_server_method'
bitcoinrpc.cpp:(.text._ZN5boost4asio3ssl7contextC1ENS1_12context_base6methodE[boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)]+0x1f1): undefined reference to `TLSv1_2_method'
collect2: ld returned 1 exit status
make: *** [feathercoin-qt] Error 1

# Solution: Custom libs should come before system libs
As system(/lib /usr/lib) includes/libs contain earlier versions of custom includes/libs(/usr/local/lib as well as libs specified on command line)

In the Makefile, this line is:
LIBS          = $(SUBLIBS)  -L/usr/lib -lqrencode /root/Feathercoin/src/leveldb/libleveldb.a /root/Feathercoin/src/leveldb/libmemenv.a -lrt -L/usr/local/boost-1.55.0/lib -L/usr/local/db-5.1.29.NC/lib -L/usr/local/openssl-1.0.1h/lib -L/usr/local/qrencode-3.4.3/lib -lssl -lcrypto -ldb_cxx -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lpthread -lQtGui -lQtNetwork -lQtCore 

This line should be:
LIBS          = $(SUBLIBS)  /root/Feathercoin/src/leveldb/libleveldb.a /root/Feathercoin/src/leveldb/libmemenv.a -L/usr/local/boost-1.55.0/lib -L/usr/local/db-5.1.29.NC/lib -L/usr/local/openssl-1.0.1h/lib -L/usr/local/qrencode-3.4.3/lib -L/usr/lib -lqrencode -lrt -lssl -lcrypto -ldb_cxx -lboost_system -lboost_filesystem -lboost_program_options -lboost_thread -lpthread -lQtGui -lQtNetwork -lQtCore 
^ This now compiles/links without errors.

**Comment by wellenreiter01** [comment]
Closing, as no comment for more than one year and related to old (0.8.7.x) release
