### ISSUE TITLE
0.9.3: Astetics - Paper Wallet Creation

### ISSUE THREAD

**Issue by uncle-muddy** [FeatherCoin/Feathercoin#69]
As reported by AmDD here https://forum.feathercoin.com/index.php?/topic/8450-feathercoin-core-wallet-093-welcome-you/page-2#entry72743

Before go live need to review the creation of paper wallets screen. As currently they are using very dated art work, logos, wording, etc..

**Comment by CalemS** [comment]
Ok. I'm on GitHub.. I thought this was a ftc forum email but okydoky.

Ok. Duly noted.

**Comment by wellenreiter01** [comment]
solved and closed
