### ISSUE TITLE
 pchMessageStart is the same as litecoin

### ISSUE THREAD

**Issue by UngarnFCP** [FeatherCoin/Feathercoin#7]
Please change pchMessageStart in main.cpp because its the same as litecoin and I got connection issues.

Also reported in https://github.com/FeatherCoin/Feathercoin-0.6.4.4/issues/35

It has to be a unique magic number and not the same as litecoin...

**Comment by wrapperband** [comment]
https://github.com/ghostlander/Phoenixcoin/commit/7d99445399481a1bac647b6df81a56a064555505

we "just" need to implement the patch that Ghostlander developed for dual magic numbers. This was supposed to get in the neoscrypt update...
