### ISSUE TITLE
0.9.3 sending coins to multisig addresses of 0.8.x clients not working

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#75]
Due to the prefix change for multi-signature addresses from '3' to 'f' it is not possible to send coins from a 0.9.3 client to a multisig address running on a 0.8.x client

**Comment by cqtenq** [comment]
I think so. Should be eliminated 0.8.x client.

**Comment by wellenreiter01** [comment]
That does not fix the problem, because the 'old' multisig addresses are exsisting even if all 0.8.x clients are gone.
coins may be lost here.

**Comment by wrapperband** [comment]
A quick fix would be to "De Multi sig" the payment in 0.8 
ie send it to a single signature address - and then update to 0.9. 

The multisig was "experimental / beta in 0.8", so very few were probably sent in reality...

**Comment by wellenreiter01** [comment]
We need to create some update documentation and mention that process.
Has anybody an idea how to publish the update process efficiently?
Also if people add the Linux repositories to their list of trusted repositories, the update may come automated.
I know for sure, that this is the case for opensuse. You still have the possibility to check upfront, but I think ,that most people simply click 'accept' ;)

**Comment by wellenreiter01** [comment]
solvet with pull request #83
