### ISSUE TITLE
0.9.3: Halving block count incorrect

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#85]
there is 210000 instead of 2100000 in the code
See discussion for pull request #84

**Comment by feathercoin2** [comment]
Yes, We must do it. it is an omission error.

**Comment by wellenreiter01** [comment]
The question is, if that piece of code ist still used, or if it is just a left over from the mining code, which is removed from the wallet, as far as I know

**Comment by wellenreiter01** [comment]
fixed with pull request #84
