### ISSUE TITLE
0.9.3 Ubuntu 14.04 package dependency issues

### ISSUE THREAD

**Issue by p1** [FeatherCoin/Feathercoin#87]
I'm unable to install the debian file on Ubuntu 14.04 Trusty because of dependency issues, boost being one of them.  I'm only issuing 2 commands from a fresh install:

wget http://download.opensuse.org/repositories/home:/wellenreiter01/xUbuntu_14.04/amd64/feathercoin_0.9.3_amd64.deb

vagrant@vagrant-ubuntu-trusty-64:~$ sudo dpkg -i feathercoin_0.9.3_amd64.deb
Selecting previously unselected package feathercoin.
(Reading database ... 62972 files and directories currently installed.)
Preparing to unpack feathercoin_0.9.3_amd64.deb ...
Unpacking feathercoin (0.9.3) ...
dpkg: dependency problems prevent configuration of feathercoin:
 feathercoin depends on libboost-filesystem1.54.0; however:
  Package libboost-filesystem1.54.0 is not installed.
 feathercoin depends on libboost-program-options1.54.0; however:
  Package libboost-program-options1.54.0 is not installed.
 feathercoin depends on libboost-system1.54.0; however:
  Package libboost-system1.54.0 is not installed.
 feathercoin depends on libboost-thread1.54.0; however:
  Package libboost-thread1.54.0 is not installed.
 feathercoin depends on libdb5.3++; however:
  Package libdb5.3++ is not installed.
 feathercoin depends on libminiupnpc8 (>= 1.6); however:
  Package libminiupnpc8 is not installed.
 feathercoin depends on libprotobuf8; however:
  Package libprotobuf8 is not installed.
 feathercoin depends on libqrencode3 (>= 3.2.0); however:
  Package libqrencode3 is not installed.
 feathercoin depends on libqt5core5a (>= 5.2.0); however:
  Package libqt5core5a is not installed.
 feathercoin depends on libqt5dbus5 (>= 5.0.2)
dpkg: error processing package feathercoin (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.54ubuntu1.1) ...
Errors were encountered while processing:
 feathercoin

**Comment by wellenreiter01** [comment]
please use 'sudo apt-get update' followed by 'sudo apt-get install feathercoin_0.9.3_amd64.deb'

This should solve dependency issues

**Comment by eris23** [comment]
I did.  The problem is conflicting dependencies.

**Comment by eris23** [comment]
I'm trying to install in Xubuntu wily.  feathercoin depends on libprotobuf9, which has been replaced by libprotobuf9v5.  They're conflicting, so there's no way to install both.  So, could you either compile for wily, or provide a static build?

**Comment by p1** [comment]
It took a bit but was finally able to automate with the following:
apt-get update
wget http://download.opensuse.org/repositories/home:/wellenreiter01/xUbuntu_14.04/amd64/feathercoin_0.9.3_amd64.deb
dpkg -i feathercoin_0.9.3_amd64.deb
cp feathercoin_0.9.3_amd64.deb /var/cache/apt/archives/
apt-get -f install
apt-get install feathercoin

I still can't compile from source, but that's a different bug for another day.  Thanks, closing
