### ISSUE TITLE
"new" transaction frequency calculation - needs correcting to 1 per min for FTC

### ISSUE THREAD

**Issue by wrapperband** [FeatherCoin/Feathercoin#88]
Just noted a bug with the daemon "transaction frequency calculation", error message, 4 * 60 = 240

not 96

**Comment by cqtenq** [comment]
Yes, I fix the problem.
https://github.com/FeatherCoin/Feathercoin/commit/5c4a3ba578f9f081c1e85b6a4daa0de693a45fdb
