### ISSUE TITLE
Make Feathercoin gui available with different skins

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#90]
Many gui offer the option to select the 'look and feel'
We should enable the gui to select skins at runtime.

**Comment by wrapperband** [comment]
This issue can be closed now.

The updates to Make the wallet compatible with the OS Themes, are available to pull from wrapperband. The Beta version is a complete version with matching icons, although it is hoped to push a few more tweaks later.

Whilst it doesn't provide full independat skins, that could be re introduced  as a possible enhancement for 0.11

**Comment by Bushstar** [comment]
We want other clients as options for people. Core client should remain somewhat vanilla.
