### ISSUE TITLE
0.11.2 Switch to upgrade to new block format is too early

### ISSUE THREAD

**Issue by wellenreiter01** [FeatherCoin/Feathercoin#93]
In the code of 0.11.2 a switch to upgrade to the new block version is performed after 100 continuous blocks in the BC are generated from the new version. This is unchanged from the original bitcoin code. Nevertheless as Bitcoin time to block is 5 minutes compared the Feathercoin's 1 minute it should be at least 500 continuous blocks before the switch

**Comment by wrapperband** [comment]
I agree, should be at least 500

**Comment by wellenreiter01** [comment]
After thinking again, I'd got for 720 = ~12 hours

**Comment by cqtenq** [comment]
where are you see  those codes ?

**Comment by cqtenq** [comment]
Check the version of the last 500 blocks to see if we need to upgrade.
main.cpp  line 2167

**Comment by wrapperband** [comment]
I messaged Wellenreiter to let you know, he must have missed it with everything else and  it's a while since I looked at that code. I'll ping him again

**Comment by wellenreiter01** [comment]
sent Lizhi the line number in skype

**Comment by wellenreiter01** [comment]
@ Lizhi, that is great :)
500/60= ~ 8 hours.
I wonder if we shouldn't go for one day or more , after the last problem with the BC.

**Comment by FeatherCoin** [comment]
fixed as per Lihi's comment
