### ISSUE TITLE
wallet synchronization stuck

### ISSUE THREAD

**Issue by AcceleratorRage** [FeatherCoin/Feathercoin#97]
I usually open my wallet every two days to update the blocks , but this time , I opened and is not updating , the first time i opened it, gave error in the connection to the network , I reopen and the error disappeared , but not is updating the number of days (2 days) and the number of blocks to synchronize ( 1,115,921 ) do not change no matter what time they pass , the signal is at most but not synchronize a block even , tried restarting the computer , close and open the wallet , but always gets the same amount of blocks for updates , this has never happened before . note : I do not know if it matters , but only happened after my first transfer , I deposited some ftc , tried to open and not updated until now.

**Comment by wrapperband** [comment]
There has been a fork due to "testing" of version. You may need to resync. Someone should be able o help with some more info ...

Which version of the wallet are you on and which operating system are you using?

**Comment by AcceleratorRage** [comment]
version 0.9.5.0-git-standard, running on a windows 10 64-bits
it's a "qt" wallet


I tried not reinstall because I made a transfer with a relatively large amount , and when I open was in this way that I reported , that is, if I re-install if I uncompensated lose value , as it is in the portfolio and I did not have any backup

**Comment by wrapperband** [comment]
The first thing you need to do is back up your wallet, that is not part of the syncing... 

I would then find the Support thread under Guides at the FTC forum, for the best advice on how to proceed.  http://forum.feathercoin.com/

**Comment by AcceleratorRage** [comment]
well , I opened now to back up , and where said " synchronizing with the server " is now showing " any available server " , which is probably the problem was just not showing the error message .

**Comment by wrapperband** [comment]
If you open the console, (help) you can type getpeerinfo (help) will tell you what connections you have

**Comment by AcceleratorRage** [comment]
[
{
"addr" : "149.202.204.56:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387941,
"lastrecv" : 1457387070,
"bytessent" : 503,
"bytesrecv" : 154,
"conntime" : 1457387070,
"pingtime" : 0.00000000,
"version" : 60008,
"subver" : "/Feathercoin:0.8.7.3/",
"inbound" : false,
"startingheight" : 691031,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "74.105.50.46:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387915,
"lastrecv" : 1457387959,
"bytessent" : 6007,
"bytesrecv" : 96634,
"conntime" : 1457387081,
"pingtime" : 0.00000000,
"version" : 60007,
"subver" : "/Satoshi:0.8.7.1/",
"inbound" : false,
"startingheight" : 1119037,
"banscore" : 0,
"syncnode" : true
},
{
"addr" : "24.211.183.101:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387674,
"lastrecv" : 1457387961,
"bytessent" : 2398,
"bytesrecv" : 94594,
"conntime" : 1457387082,
"pingtime" : 0.00000000,
"version" : 60007,
"subver" : "/Satoshi:0.8.7.1/",
"inbound" : false,
"startingheight" : 1119037,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "101.200.198.233:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457387985,
"lastrecv" : 1457388032,
"bytessent" : 2563,
"bytesrecv" : 49674,
"conntime" : 1457387094,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Satoshi:0.9.5/",
"inbound" : false,
"startingheight" : 1119037,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "195.166.157.97:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457388022,
"lastrecv" : 1457387960,
"bytessent" : 3648,
"bytesrecv" : 94666,
"conntime" : 1457387122,
"pingtime" : 0.00000000,
"version" : 60007,
"subver" : "/Satoshi:0.8.7.1/",
"inbound" : false,
"startingheight" : 1119038,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "176.31.126.191:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387975,
"lastrecv" : 1457387959,
"bytessent" : 3362,
"bytesrecv" : 98131,
"conntime" : 1457387123,
"pingtime" : 0.00000000,
"version" : 60008,
"subver" : "/Feathercoin:0.8.7.3/",
"inbound" : false,
"startingheight" : 1119038,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "104.236.34.9:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457387850,
"lastrecv" : 1457387959,
"bytessent" : 2660,
"bytesrecv" : 95231,
"conntime" : 1457387140,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Satoshi:0.9.3/",
"inbound" : false,
"startingheight" : 1119038,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "198.48.192.232:9336",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457388062,
"lastrecv" : 1457387960,
"bytessent" : 2679,
"bytesrecv" : 95037,
"conntime" : 1457387141,
"pingtime" : 0.00000000,
"version" : 60007,
"subver" : "/Satoshi:0.8.7/",
"inbound" : false,
"startingheight" : 1119038,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "76.167.46.183:56714",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387673,
"lastrecv" : 1457387959,
"bytessent" : 98076,
"bytesrecv" : 680813,
"conntime" : 1457387181,
"pingtime" : 0.00000000,
"version" : 60007,
"subver" : "/Satoshi:0.8.7.1/",
"inbound" : true,
"startingheight" : 1118107,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "192.99.4.195:38057",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457387483,
"lastrecv" : 1457387297,
"bytessent" : 30341,
"bytesrecv" : 229,
"conntime" : 1457387292,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Potcoin:0.8.7.1/",
"inbound" : true,
"startingheight" : 974999,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "51.254.199.21:47726",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457387486,
"lastrecv" : 1457387959,
"bytessent" : 32407,
"bytesrecv" : 19528,
"conntime" : 1457387412,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Satoshi:0.9.3/",
"inbound" : true,
"startingheight" : 1119042,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "70.163.93.50:32848",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000003",
"lastsend" : 1457388054,
"lastrecv" : 1457388073,
"bytessent" : 30237,
"bytesrecv" : 5016,
"conntime" : 1457387479,
"pingtime" : 0.00000000,
"version" : 70004,
"subver" : "/Satoshi:0.8.6.2/",
"inbound" : true,
"startingheight" : 472548,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "128.8.124.7:37866",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457388060,
"lastrecv" : 1457388041,
"bytessent" : 720907,
"bytesrecv" : 1059,
"conntime" : 1457387678,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/UMDCoinscope:0.0/",
"inbound" : true,
"startingheight" : 783913,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "31.173.212.134:35397",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457387986,
"lastrecv" : 1457388059,
"bytessent" : 31371,
"bytesrecv" : 18505,
"conntime" : 1457387938,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Satoshi:0.9.3/",
"inbound" : true,
"startingheight" : 1119055,
"banscore" : 0,
"syncnode" : false
},
{
"addr" : "46.166.186.234:13278",
"addrlocal" : "179.35.79.44:9336",
"services" : "00000001",
"lastsend" : 1457388066,
"lastrecv" : 1457388067,
"bytessent" : 59074,
"bytesrecv" : 127629,
"conntime" : 1457387982,
"pingtime" : 0.00000000,
"version" : 70002,
"subver" : "/Satoshi:0.8.5.3/",
"inbound" : true,
"startingheight" : 6747396,
"banscore" : 0,
"syncnode" : false
}
]
